FROM oven/bun:latest

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      curl jq openssl ca-certificates procps \
      nodejs npm \
 && rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]
