// systemd unit file generation + systemctl wrapper. Opt-in only — never
// invoked from default install path. Replaces bash here-doc + systemctl
// calls with TS string templates + spawnSync.

import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { InstallError } from "./log.ts";

export type ServiceName = "ework-web" | "ework-daemon";

export interface UnitContext {
  user: string;
  group: string;
  binPath: string;            // resolved binary path (e.g. /home/u/.bun/bin/bun)
  mainScript: string;         // entry script (e.g. /usr/lib/node_modules/ework-web/bin/ework-web.js)
  envFile: string;
  workingDirectory: string;
  // Absolute path the service should pipe stdout/stderr to. Must match the
  // PID-file mode log path (paths.webLogFile / paths.daemonLogFile) so
  // `ework-aio logs <svc>` reads the same file regardless of how the
  // service was started.
  logFile: string;
  restart?: "always" | "on-failure" | "no";
  description?: string;
}

export function generateUnitFile(svc: ServiceName, ctx: UnitContext): string {
  const restart = ctx.restart ?? "always";
  const description = ctx.description ?? (svc === "ework-web" ? "ework-web (issue tracker)" : "ework-daemon (AI bridge)");

  return `# Generated by ework-aio. Edits will be overwritten on next install.
[Unit]
Description=${description}
After=network.target

[Service]
Type=simple
User=${ctx.user}
Group=${ctx.group}
WorkingDirectory=${ctx.workingDirectory}
EnvironmentFile=${ctx.envFile}
ExecStart=${ctx.binPath} ${ctx.mainScript}
Restart=${restart}
RestartSec=3
StandardOutput=append:${ctx.logFile}
StandardError=append:${ctx.logFile}

[Install]
WantedBy=default.target
`;
}

export async function writeUnitFile(unitFile: string, content: string): Promise<void> {
  const dir = path.dirname(unitFile);
  await fs.promises.mkdir(dir, { recursive: true });
  const tmp = path.join(dir, `.unit.tmp.${process.pid}.${Date.now()}`);
  await fs.promises.writeFile(tmp, content, { mode: 0o644 });
  try {
    await fs.promises.rename(tmp, unitFile);
  } catch (err) {
    await fs.promises.unlink(tmp).catch(() => {});
    throw err;
  }
}

export interface SystemctlOptions {
  scope: "user" | "system";
  // If scope=user, whether to also run `loginctl enable-linger` (only meaningful for user mode).
  enableLinger?: boolean;
  // For tests: override systemctl binary path.
  systemctlBin?: string;
  // For tests: capture stdout/stderr of invocations.
  captureIO?: boolean;
}

export interface SystemctlResult {
  exitCode: number;
  stdout: string;
  stderr: string;
}

function systemctlBase(opts: SystemctlOptions): string {
  return opts.systemctlBin ?? "systemctl";
}

function systemctlArgs(opts: SystemctlOptions, args: string[]): string[] {
  return opts.scope === "user" ? ["--user", ...args] : args;
}

export function runSystemctl(args: string[], opts: SystemctlOptions): SystemctlResult {
  const bin = systemctlBase(opts);
  const fullArgs = systemctlArgs(opts, args);
  const r = spawnSync(bin, fullArgs, {
    encoding: "utf8",
    // For --user scope, XDG_RUNTIME_DIR must be set; caller's env has it.
    env: process.env,
  });
  return {
    exitCode: r.status ?? -1,
    stdout: r.stdout ?? "",
    stderr: r.stderr ?? "",
  };
}

// install_unit: writes unit file, runs daemon-reload + enable. Atomic — if
// any systemctl call fails, returns the error without leaving half-state.
// Caller decides whether to roll back (delete the unit file).
export async function installUnit(svc: ServiceName, unitFile: string, content: string, opts: SystemctlOptions): Promise<void> {
  await writeUnitFile(unitFile, content);

  const reload = runSystemctl(["daemon-reload"], opts);
  if (reload.exitCode !== 0) {
    throw new InstallError(
      `systemctl daemon-reload failed for ${svc}: ${reload.stderr.trim() || reload.stdout.trim()}`,
    );
  }

  const enable = runSystemctl(["enable", `${svc}.service`], opts);
  if (enable.exitCode !== 0) {
    throw new InstallError(
      `systemctl enable ${svc} failed: ${enable.stderr.trim() || enable.stdout.trim()}`,
    );
  }
}

export async function startUnit(svc: ServiceName, opts: SystemctlOptions): Promise<void> {
  const r = runSystemctl(["start", `${svc}.service`], opts);
  if (r.exitCode !== 0) {
    throw new InstallError(
      `systemctl start ${svc} failed: ${r.stderr.trim() || r.stdout.trim()}`,
    );
  }
}

export async function stopUnit(svc: ServiceName, opts: SystemctlOptions): Promise<void> {
  // stop is best-effort — ignore "unit not loaded" errors
  const r = runSystemctl(["stop", `${svc}.service`], opts);
  if (r.exitCode !== 0 && !/not loaded/i.test(r.stderr)) {
    throw new InstallError(
      `systemctl stop ${svc} failed: ${r.stderr.trim() || r.stdout.trim()}`,
    );
  }
}

export async function disableUnit(svc: ServiceName, opts: SystemctlOptions): Promise<void> {
  const r = runSystemctl(["disable", `${svc}.service`], opts);
  if (r.exitCode !== 0 && !/not loaded/i.test(r.stderr)) {
    throw new InstallError(
      `systemctl disable ${svc} failed: ${r.stderr.trim() || r.stdout.trim()}`,
    );
  }
}

export type ServiceState = "active" | "inactive" | "failed" | "unknown";

export function getUnitState(svc: ServiceName, opts: SystemctlOptions): ServiceState {
  const r = runSystemctl(["is-active", `${svc}.service`], opts);
  const out = r.stdout.trim().toLowerCase();
  if (r.exitCode === 0) return "active";
  if (out === "inactive" || out === "deactivating") return "inactive";
  if (out === "failed") return "failed";
  return "unknown";
}

export async function removeUnit(svc: ServiceName, unitFile: string, opts: SystemctlOptions): Promise<void> {
  await disableUnit(svc, opts);
  await stopUnit(svc, opts);
  const r = runSystemctl(["daemon-reload"], opts);
  if (r.exitCode !== 0) {
    // reload failure is non-fatal during uninstall
  }
  try {
    await fs.promises.unlink(unitFile);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
  }
}
